### ISSUE TITLE
When I run the project encountered some problems 

### ISSUE THREAD

**Issue by ZYCheng-coder** [pranavkdm/R-PointHop#1]
1.
python train.py --first_20 False
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    main()
  File "train.py", line 42, in main
    train_data = train_data[train_label<20]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1024 but corresponding boolean dimension is 1

2.
python test.py --source ./data/source_0.ply --target ./data/target_0.ply
munmap_chunk(): invalid pointer
(core dumped) 

Is it because of the version of the installation library? 

Could you tell me about your library version?

**Comment by pranavkdm** [comment]
Hi, there was a small issue which has been resolved. Thanks for pointing out. You can try now.

**Comment by sun6s** [comment]
data_c = np.concatenate((target_e,source_e), axis=0)
all the input array dimensions for the concatenation axis must match exactly, how to register point cloud in different  sizes?

**Comment by pranavkdm** [comment]
> data_c = np.concatenate((target_e,source_e), axis=0)
> all the input array dimensions for the concatenation axis must match exactly, how to register point cloud in different sizes?

Hi,

The model has been trained with 1024 points. I can suggest two options here. One is to downsample the point clouds so that they contain 1024 points. You can find the downsampling function furthest_point_sample() in point_utils.py. Else more generally, you can pass each point cloud separately through the feature extractor. This can be done by calling the pointhop_pred() function from rpointhop.py separately for the two point clouds. 

Thanks!

**Comment by sun6s** [comment]
Thanks a lot, but it got failed when I try to align two incompletely overlapping point clouds, like bun045.ply and bun000.ply.&nbsp;

孙志亮


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pranav ***@***.***&gt;; 
发送时间: 2021年3月26日(星期五) 凌晨4:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pranavkdm/R-PointHop] When I run the project encountered some problems  (#1)



data_c = np.concatenate((target_e,source_e), axis=0)
 all the input array dimensions for the concatenation axis must match exactly, how to register point cloud in different sizes?
  Hi,
 The model has been trained with 1024 points. I can suggest two options here. One is to downsample the point clouds so that they contain 1024 points. You can find the downsampling function furthest_point_sample() in point_utils.py. Else more generally, you can pass each point cloud separately through the feature extractor. This can be done by calling the pointhop_pred() function from rpointhop.py separately for the two point clouds.
 Thanks!

**Comment by pranavkdm** [comment]
> Thanks a lot, but it got failed when I try to align two incompletely overlapping point clouds, like bun045.ply and bun000.ply.&nbsp; 孙志亮 &nbsp;

I understand. Since the model is not trained on Stanford bunny you may want to vary the set of parameters like neighborhood size, number of downsampled points etc. The experiments in the paper use 2048 points in each point cloud for bunny dataset with a larger neighborhood size than ModelNet40.
